# Generated by Django 3.2.3 on 2021-05-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banda', models.CharField(max_length=100)),
                ('Disco', models.CharField(max_length=40)),
                ('Ano', models.CharField(max_length=20)),
                ('Gravadora', models.CharField(max_length=20)),
            ],
        ),
    ]
